kvm_ethernet_bridge_interface: "enp1s0"
kvm_bridge_name: "br1"
domain: 'server02.lan'
network_ip: "10.0.0.0"
gateway_ip: "10.0.1.1"
server_ip: "10.0.1.200"
subnet: "24"
network_address: "{{ network_ip }}/{{ subnet }}"
longhorn_data_dir: "/data/longhorn"
