---
- name: "Create nfs directories"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_recipes }}/nfs"
    - "{{ docker_share }}/nfs"

- name: "Generate nfs docker-compose file"
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_recipes }}/nfs/docker-compose.yml"

- name: "Deploy nfs"
  docker_compose:
    project_src: '{{ docker_recipes }}/nfs'
    files:
    - docker-compose.yml
    remove_orphans: true
