---
- name: "Create sftp directories"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_recipes }}/sftp"
    - "{{ docker_data }}/sftp"
    - "{{ docker_share }}"

- name: "Generate sftp docker-compose file"
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_recipes }}/sftp/docker-compose.yml"

- name: "Get Encrypted sftp Password"
  ansible.builtin.shell:
    cmd: "python -c \"import crypt; print(crypt.crypt('{{ webservices_password }}'))\""
  register: sftp_pw

- name: "Store Encrypted sftp Password"
  set_fact:
    sftp_encrypted_password: "{{ sftp_pw.stdout }}"

- name: "Generate sftp config"
  template:
    src: "{{ item }}"
    dest: "{{ docker_data }}/sftp/{{ item | basename | regex_replace('\\.j2$', '') }}"
  with_items:
    - "users.conf.j2"

- name: "Deploy sftp"
  docker_compose:
    project_src: '{{ docker_recipes }}/sftp'
    files:
    - docker-compose.yml
    remove_orphans: true
