---
- name: "Create public-services directories"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_recipes }}/public-services"
    - "{{ docker_data }}/public-services"
    - "{{ docker_data }}/public-services/tailscale"
    - "{{ docker_data }}/public-services/vaultwarden"
    - "{{ docker_data }}/public-services/gitea"
    - "{{ docker_data }}/public-services/traefik"
    - "{{ docker_data }}/public-services/traefik/config"
    - "{{ docker_data }}/public-services/traefik/certs"
    - "{{ docker_data }}/public-services/traefik/log"

- name: "Copy tailscale-relay buildfiles"
  copy:
    src: "files/tailscale-relay"
    dest: "{{ docker_recipes }}/public-services"
    owner: "{{ username }}"
    group: "docker"
    mode: 0755

- name: "Generate public-services docker-compose file"
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_recipes }}/public-services/docker-compose.yml"

- name: "Generate traefik config"
  template:
    src: "{{ item }}"
    dest: "{{ docker_data }}/public-services/traefik/config/{{ item | basename | regex_replace('\\.j2$', '') }}"
  with_items:
    - "config.yml.j2"
    - "traefik.yml.j2"

- name: "Generate docker-compose environment variables file"
  template:
    src: env.j2
    dest: "{{ docker_recipes }}/public-services/.env"
    force: no

- name: "Build tailscale-relay image"
  docker_image:
    name: public-services_tailscale
    build:
      path: "{{ docker_recipes }}/public-services/tailscale-relay"
    source: build
    # force_source: true

- name: "Deploy public-services"
  docker_compose:
    project_src: '{{ docker_recipes }}/public-services'
    files:
    - docker-compose.yml
    remove_orphans: true
