---

- block:

  - name: "Update OPNsense"
    command: /usr/local/etc/rc.firmware

  # - name: "Reboot to complete update"
  #   reboot:
  #     reboot_command: /usr/local/etc/rc.firmware
  #     reboot_timeout: 50
  #     connect_timeout: 50

  - name: "Install opnsense plugins"
    command:
      cmd: "/usr/local/opnsense/scripts/firmware/install.sh {{ item }}"
    with_items: "{{ opn_plugins | default([]) }}"

  - name: "Reload services and webgui"
    command: "{{ item }}"
    with_items:
        - configctl service reload all
        - configctl webgui restart

  become: yes
