---
- name: "Create authelia directories"
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ docker_recipes }}/authelia"
    - "{{ docker_data }}/authelia"

- name: "Generate authelia config"
  template:
    src: "{{ item }}"
    dest: "{{ docker_data }}/authelia/{{ item | basename | regex_replace('\\.j2$', '') }}"
    # force: off
  become: yes
  with_items:
    - "configuration.yml.j2"
    - "users_database.yml.j2"

- name: "Generate authelia docker-compose file"
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_recipes }}/authelia/docker-compose.yml"

- name: "Deploy authelia"
  docker_compose:
    project_src: '{{ docker_recipes }}/authelia'
    files:
    - docker-compose.yml
