---
- name: "Create code-server directories"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_recipes }}/code-server"
    - "{{ docker_data }}/code-server"

- name: "Generate code-server docker-compose file"
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_recipes }}/code-server/docker-compose.yml"

- name: "Deploy code-server"
  docker_compose:
    project_src: '{{ docker_recipes }}/code-server'
    files:
    - docker-compose.yml
    remove_orphans: true
