---
- name: "Create traefik directories"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_recipes }}/traefik"
    - "{{ docker_data }}/traefik"
    - "{{ docker_data }}/traefik/config"
    - "{{ docker_data }}/traefik/log"
    - "{{ certs_path }}"

- name: "Generate traefik docker-compose file"
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_recipes }}/traefik/docker-compose.yml"

- name: "Generate traefik config"
  template:
    src: "{{ item }}"
    dest: "{{ docker_data }}/traefik/config/{{ item | basename | regex_replace('\\.j2$', '') }}"
  with_items:
    - "config.yml.j2"
    - "traefik.yml.j2"

- name: "Deploy traefik"
  docker_compose:
    project_src: '{{ docker_recipes }}/traefik'
    files:
    - docker-compose.yml
    remove_orphans: true
