---
- name: "Create libvirt directories"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ libvirt_home }}"
    - "{{ libvirt_vms }}"

- name: "Check if vyos image {{ libvirt_vms }}/{{ vyos_qcow2_filename }} exists"
  stat:
    path: "{{ libvirt_vms }}/{{ vyos_qcow2_filename }}"
  register: stat_vyos_image

- block:
  - name: "Generate VyOS image (this may take a while)"
    command:
      cmd: "docker run -t --rm --privileged -v /dev:/dev -v /tmp:/output --pull=always ghcr.io/niki-on-github/vyos-qemu-images:dev"

  - name: "Rename VyOS image"
    shell:
      cmd: "mv -fv /tmp/vyos-*-qemu.qcow2 {{ libvirt_vms }}/{{ vyos_qcow2_filename }}"

  - name: "Ensure VyOS image permissions"
    file:
      path: "{{ libvirt_vms }}/{{ vyos_qcow2_filename }}"
      owner: "{{ uid }}"
      group: "{{ gid }}"
      mode: "0755"

  when: not stat_vyos_image.stat.exists
  become: true

- name: "Start default network"
  shell:
    cmd: virsh --connect qemu:///system net-start default
  failed_when: false

- name: "Set autostart for default network"
  shell:
    cmd: virsh --connect qemu:///system net-autostart default

# NOTE: delete with `virsh --connect qemu:///system undefine vyos`
- name: "Check if VyOS VM is already created"
  shell:
    cmd: virsh --connect qemu:///system list --name | grep -q "^vyos$"
  register: vyos_vm
  failed_when: false

- name: "Create VyOS VM"
  shell:
    cmd: >
      virt-install -n vyos \
       --connect "qemu:///system" \
       --ram 2048 \
       --vcpus 2 \
       --os-variant debian10 \
       --network network=default \
       --graphics vnc \
       --hvm \
       --virt-type kvm \
       --disk path={{ libvirt_vms }}/{{ vyos_qcow2_filename }},bus=virtio \
       --import \
       --autostart \
       --noautoconsole
  when: vyos_vm.rc != 0

- name: "Start VyOS VM"
  community.libvirt.virt:
    name: vyos
    state: running

- name: "Show Post Install Message"
  ansible.builtin.debug:
    msg: "Use `virsh --connect qemu:///system console vyos` to connect to vm with default user `vyos` and password `vyos`"
