kvm_ethernet_bridge_interface: "eno3"
kvm_bridge_name: "br1"
domain: 'server01.lan'
network_ip: "10.0.1.0"
gateway_ip: "10.0.1.1"
server_ip: "10.0.1.10"
subnet: "24"
network_address: "{{ network_ip }}/{{ subnet }}"

# use lsusb [<vendor>]:[<product>]
# opnsense_usb_dev: "libvirt.usb :vendor => '0x0b95', :product => '0x7720'"

# use lspci [<domain>]:[<bus>]:[<slot>].[<func>]
opnsense_pci_dev: |
  libvirt.pci :domain => '0x0000', :bus => '0x04', :slot => '0x00', :function => '0x0'
  libvirt.pci :domain => '0x0000', :bus => '0x04', :slot => '0x00', :function => '0x1'

opnsense_dhcp_server_enabled: true

dev1: "/dev/sda"
dev2: "/dev/sdb"
label: "data01"
mountpoint: "/mnt/backup"
