---
- name: "Create wireguard-server directories"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_recipes }}/wireguard-server"
    - "{{ docker_data }}/wireguard-server"

- name: "Generate wireguard-server docker-compose file"
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_recipes }}/wireguard-server/docker-compose.yml"

- name: "Attempt to deploy wireguard-server"
  block:
    - name: "Deploy wireguard-server"
      docker_compose:
        project_src: '{{ docker_recipes }}/wireguard-server'
        files:
        - docker-compose.yml
        remove_orphans: true
  rescue:
      - name: "Print error message"
        debug:
          msg: 'If ansible have install a new kernel you have to reboot to get a working wireguard-server kernel module for this docker container!'


