kvm_ethernet_bridge_interface: "eno3"
kvm_bridge_name: "br1"
domain: 'server01.lan'
network_ip: "10.0.1.0"
gateway_ip: "10.0.1.1"
server_ip: "10.0.1.10"
subnet: "24"
network_address: "{{ network_ip }}/{{ subnet }}"

# use lspci [<domain>]:[<bus>]:[<slot>].[<func>]
opnsense_pci_dev: |
  libvirt.pci :domain => '0x0000', :bus => '0x04', :slot => '0x00', :function => '0x0'
  libvirt.pci :domain => '0x0000', :bus => '0x04', :slot => '0x00', :function => '0x1'

opnsense_wan_interface: "igb0"
opnsense_lan_interface: "vtnet0"
opnsense_dhcp_server_enabled: true

storage_dev1: "/dev/sda"
storage_dev2: "/dev/sdb"
storage_label: "data01"
storage_mountpoint: "/mnt/backup"

