---
- name: "Create pxe-server directories"
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ docker_recipes }}/pxe-server"
    - "{{ docker_recipes }}/pxe-server/container"

- name: "Generate pxe-server Dockerfile"
  template:
    src: Dockerfile.j2
    dest: "{{ docker_recipes }}/pxe-server/container/Dockerfile"

- name: "Generate pxe-server docker-compose file"
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_recipes }}/pxe-server/docker-compose.yml"

- name: "Deploy pxe-server"
  docker_compose:
    project_src: '{{ docker_recipes }}/pxe-server'
    files:
    - docker-compose.yml
