---
- hosts: archlinux, ubuntu, nixos
  roles:
    - role: linux/docker
    - role: linux/backup
    - role: linux/certificate
    - role: containers/core/all
    - role: containers/services/all
    - role: containers/apps/all

