---
- hosts: archlinux
  roles:

    # system
    - role: archlinux/system
    - role: archlinux/docker

    # first install traefik
    - role: all/containers/traefik
    - role: all/containers/all

