---
- hosts: archlinux, nixos
  roles:
    # - role: archlinux/precondition
    # - role: archlinux/ssh-agent
    # - role: linux/docker
    - role: linux/certificate
    - role: linux/develop/k3s-clean
    - role: archlinux/k3s

