---
- hosts: archlinux
  roles:

    # system
    - role: archlinux/system
    - role: linux/docker
    - role: archlinux/kvm
    - role: archlinux/network/kvm-bridge

    # VMs
    - role: vms/opnsense-install
