---
- block:
  # root

  - name: 'Create backup directories'
    file:
      dest: "{{ item }}"
      state: directory
      owner: "{{ uid }}"
      group: "{{ gid }}"
      recurse: no
    with_items:
       - "{{ backup_home }}"
       - "{{ backup_home }}/borg"
       - "{{ docker_backup }}"
       - "{{ docker_logs }}"

  - name: 'Install backup packages'
    package:
      name:
        - borg
        - rsync
      state: latest

  - name: "Create backup service config"
    template:
      src: backup.service.j2
      dest: "/etc/systemd/system/backup.service"
      owner: root
      group: root
      mode: 0640

  - name: "Create backup timer config"
    template:
      src: backup.timer.j2
      dest: "/etc/systemd/system/backup.timer"
      owner: root
      group: root
      mode: 0640

  - name: "Create backup script {{ backup_script }}"
    template:
      src: backup.sh.j2
      dest: "{{ backup_script }}"
      owner: root
      group: root
      mode: 0750

  - name: "Enable backup timer"
    systemd:
      name: "backup.timer"
      state: started
      enabled: true
      daemon_reload: true

  become: yes
